Feature/dillontest
SoftStackFactory/PersonaTest-UI pull request #51
Opened 2017-08-03 01:58 UTC by tecumseh619

Test-lists html and flexbox cess styling

2017-08-03 02:11 UTC, SalMac86 commented on src/pages/test-lists/test-lists.scss
> +      min-height: 100vh;
we may want to include a max-height

2017-08-03 02:13 UTC, SalMac86 approved these changes

2017-08-03 02:13 UTC, SalMac86 requested changes
fix view height max

2017-08-08 19:17 UTC, phortonssf commented
Looking good just. I will merge these changes in. Just work on those change we talked about:
ngFor, centering with margin, using the color global colors;

2017-08-08 19:22 UTC, merged